#
#      .d88888b           d88888P                   d88888P d88  d88
#      88.    "'              d8'                       d8'  88   88
#      `Y88888b. .d8888b.    d8'  .d8888b. 88d888b.    d8'   88   88
#            `8b 88ooood8   d8'   88ooood8 88'  `88   d8'    88   88
#      d8'   .8P 88.  ...  d8'    88.  ... 88    88  d8'     88   88
#       Y88888P  `88888P' d8'     `88888P' dP    dP d8'     d88P d88P
#
#         Original plugin by DXM_Hip. Updated to API 3 by Se7en711

#DO NOT CHANGE THE VERSION !
Version: 2.0
#Time (in minutes) for a player to be kicked if he's AFK
Time: 30
#Message to be displayed when the player is kicked for being AFK
#You can use § for color formatting
Kick-Message: "§4§l[§fStopAFK§4] §r§cYou've been kicked for being AFK for 30 minutes."
#Scan-Interval is the time in seconds to check all players movement
#This can be set between 1 and 30 seconds
#Recommended scan interval is 10 seconds
#Set the scan interval to a higher value if you have a slow server to avoid lag.
#Set the scan interval to a lower value if your server has low TPS ! Example : if your server constantly has 10 TPS and you want the plugin to scan movement every 10 seconds, set the scan interval to 5
Scan-Interval: 10
